### PR TITLE
Add lg/md size

### PR DESCRIPTION
**Pull request by FernandezMathieu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by FernandezMathieu** [comment]
@conda-forge/core Hello can someone validate this PR and the 4 others please : 
- https://github.com/conda-forge/spacy-model-es-feedstock/pull/10
- https://github.com/conda-forge/spacy-model-fr-feedstock/pull/10
- https://github.com/conda-forge/spacy-model-it-feedstock/pull/8
- https://github.com/conda-forge/spacy-model-nl-feedstock/pull/8

**Comment by FernandezMathieu** [comment]
@cbrueffer can you eventually help me about my last comment here ?

**Comment by FernandezMathieu** [comment]
@dbast sorry i know you are not one of the repository maintainers but can you merge this ? and the others like i described here https://github.com/conda-forge/spacy-model-de-feedstock/pull/11#issuecomment-973965028

**Comment by FernandezMathieu** [comment]
@conda-forge-admin, please ping team

**Comment by mxr-conda** [comment]
Thanks, @FernandezMathieu!

**Pull request merged**
